version: '3.8'

networks:
  hie:
    driver: bridge

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: "certbot certonly --standalone -n --agree-tos --email help@uwdigi.org -d sgs.uwdigi.org"
    volumes:
     - certs:/etc/letsencrypt
    ports:
     - 80:80
     - 443:443

volumes:
  certs: ~