version: "3.7"

services:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    depends_on:
      - gateway
    volumes:
      - ./gateway/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

  gateway:
    image: itechuw/sgs-gateway:latest
    build:
      context: ./gateway/    
    restart: "unless-stopped"
    container_name: sgs-gateway
    environment:
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./gateway/etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot:ro
 
volumes:
  certbot: