version: "3.7"

services:
  gateway:
    image: sgs/gateway:${TAG:-v1.0.0}
    build:
      context: ./gateway/    
    restart: "unless-stopped"
    container_name: sgs-gateway
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
 
  outcomes:
    image: sgs/outcomes:${TAG:-v1.0.0}
    restart: "unless-stopped"
    container_name: sgs-outcomes
    depends_on:
      - backend 
      - proxy
    ports:
      - "3000:3000"  

  proxy:
    image: sgs/proxy:${TAG:-v1.0.0}
    restart: "unless-stopped"
    container_name: sgs-proxy
    ports:
      - "5000:5000" 
    env_file:
      - .env      

  frontend:
    image: sgs/frontend:${TAG:-v1.0.0}
    build:
      context: ./frontend/
    restart: "unless-stopped"
    container_name: sgs-frontend
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/sgs_config.json
      SPA_DEFAULT_LOCALE:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend
    volumes:
      - ./frontend/sgs_config.json:/usr/share/nginx/html/sgs_config.json

  backend:
    image: sgs/backend:${TAG:-v1.0.0}
    build:
      context: .
    restart: "unless-stopped"
    container_name: sgs-backend
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs_data:/openmrs/data
      - ./distro/configuration/:/openmrs/distribution/openmrs_config
    env_file:
      - .env

  # MariaDB
  db:
    image: mariadb:10.8.2
    restart: "unless-stopped"
    container_name: sgs-mariadb
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro

volumes:
  openmrs_data: ~
  db_data: ~
  certs:
