name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/sgs-gateway:latest

      # Build and push the Docker image
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/sgs-frontend:latest

      # Build and push the Docker image
      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/sgs-backend:latest          